config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#index'

  resources :people
  resources :drawings, only: [:index, :create, :show, :destroy]
  get 'drawing/:id/redraw', to: 'drawings#redraw', as: 'redraw'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drawing.rb
class Drawing < ApplicationRecord
  validates :year, presence: true, uniqueness: true

  has_many :selections, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :selections

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :drawing
  belongs_to :presenter, class_name: 'Person', foreign_key: 'presenter_id'
  belongs_to :presentee, class_name: 'Person', foreign_key: 'presentee_id'

  validates :presenter, presence: true
  validates :presenter, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index; end
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_action :set_drawing, only: [:show, :destroy, :redraw]
  def index
    @current_year = Time.current.year
    @drawings = Drawing.all.order('year ASC')
  end

  def create
    @drawing = Drawing.new(drawing_params)
    do_drawing
    if @drawing.save
      redirect_to drawings_path, notice: 'Successfully created drawing!'
    else
      redirect_to drawings_path, notice: @drawing.errors.full_messages.first
    end

  end

  def show; end

  def destroy
    @drawing.destroy
    redirect_to drawings_path, notice: 'Drawing destroyed'
  end

  def redraw
    params[:year] = @drawing.year
    @drawing.destroy
    create
  end

  private

    def drawing_params
      params.permit(:year)
    end

    def set_drawing
      @drawing = Drawing.find(params[:id])
    end

    def do_drawing
      selections = Person.all.to_a
      valid = false
      while not valid
        selections.shuffle!
        valid = isValid(selections)
      end
      selections.each_with_index do |presenter, i|
        Selection.create(presenter: presenter, 
          presentee: selections[(i+1) % selections.length], drawing: @drawing)
      end
    end

    # given an array of people, checks if the ordering is valid
    def isValid(people)
      people.each_with_index do |presenter, i| 
        if presenter.last_name == people[(i + 1) % people.length].last_name
          return false
        end
      end
      return true
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all.order(:last_name)
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name)
    end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  # def index
  #   @selections = Selection.all
  #   # TODO make sure this works
  #   @selections.joins(:people).order('presenter.id DESC')
  # end

  # def create
  #   @selection = Selection.new(selection_params)
  #   if not @selection.save
  #     flash['notice'] = 'Failed to create selection'
  #   end
  # end

  private

    def selection_params
      params.require(:selection).permit(:presenter, :presentee)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/application/_nav.html.erb
<%= link_to 'People', people_path, method: :get %>
<%= link_to 'Drawings', drawings_path, method: :get %>
<br>
--------------------------------------------------------------

app/views/dashboards/index.html.erb
<h1>Secret Santa App</h1>

<%= button_to 'New Drawing', drawings_path, method: :post %>

app/views/drawings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drawings</h1>

<%= button_to "Create Drawing for #{@current_year}", drawings_path(year: @current_year) %>

<table>

  <tbody>
    <% @drawings.each do |drawing| %>
      <tr>
        <td><%= link_to drawing.year, drawing %></td>
        <td><%= link_to 'Destroy', drawing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/drawings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @drawing.year %>
</p>

<p>
  <strong>Selections</strong>
  <table>
    <thead>
      <tr>
          <th>Presenter</th>
          <th>Presentee</th>
      </tr>
    </thead>

    <tbody>
      <% @drawing.selections.each do |selection| %>
        <tr>
          <td><%= selection.presenter.first_name %></td>
          <td><%= selection.presentee.first_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>

<%= link_to 'Redraw', redraw_path, method: :get, data: { confirm: 'Are you sure?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'nav' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.select :last_name, options_for_select([['Basile', 'Basile'], ['Callahan', 'Callahan'], ['Craven', 'Craven']]) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/selections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Selections for TODO:Insert Year</h1>

<table>
  <thead>
    <tr>
      <th>Presenter</th>
      <th>Presentee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @selections.each do |selection| %>
      <tr>
        <td><%= selection.presenter %></td>
        <td><%= selection.presentee %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>